type Query {
  "A curated array of listings of feature on the homepage"
  featuredListings: [Listing!]!
  "Fetch a Listing's details"
  listing(id: ID!): Listing
}

type Mutation {
  "Create a new listing"
  createListing(input: CreateListingInput!): CreateListingResponse!
}

input CreateListingInput {
  title: String!
  description: String!
  numOfBeds: Int!
  costPerNight: Float!
  closedForBookings: Boolean
  amenities: [ID!]!
}

"A particular intergalactic location available for booking"
type Listing {
  id: ID!
  title: String!
  description: String!
  numOfBeds: Int
  costPerNight: Float
  closedForBookings: Boolean
  amenities: [Amenity!]!
}

type Amenity {
  id: ID!
  category: String!
  name: String!
}

type CreateListingResponse {
  code: Int!
  success: Boolean!
  message: String!
  listing: Listing
}
